### ISSUE TITLE
如何实现用shift键切换英文输入和国际音标输入呢？

### ISSUE THREAD

**Issue by heyoujue** [rime/rime-ipa#9]
在写英文论文的时候，想要实现英文字母和国际音标的快速切换。但目前这个schema文件无法实现用shift来切换，应该在` ipa_yunlong.schema.yaml`添加什么语句呢？

**Comment by heyoujue** [comment]
自问自答一下：
`ipa_yunlong.schema.yaml`中添加`switches`如下：
```
switches:
  - name: ascii_mode
    reset: 0
    states: [ 音标, 西文 ]
```

同时在`engine`的`processors`下添加`- ascii_composer`：

```
engine:
  processors:
    - ascii_composer
```
